-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "currentExp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "freePoints" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1;
